In [1]:
import pandas as pd

LOAD DATASET

In [2]:
#load dataset

df=pd.read_csv("../dataset/Dataset.csv")
#.. means go one folder back from notebooks
# then enter dataset

In [3]:
df.head()

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,270
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,Botswana Pula(P),No,No,No,No,4,4.9,Dark Green,Excellent,365
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,Botswana Pula(P),Yes,No,No,No,4,4.8,Dark Green,Excellent,229

In [4]:
df.shape

(9551, 21)

In [5]:
df.columns

Index(['Restaurant ID', 'Restaurant Name', 'Country Code', 'City', 'Address',
       'Locality', 'Locality Verbose', 'Longitude', 'Latitude', 'Cuisines',
       'Average Cost for two', 'Currency', 'Has Table booking',
       'Has Online delivery', 'Is delivering now', 'Switch to order menu',
       'Price range', 'Aggregate rating', 'Rating color', 'Rating text',
       'Votes'],
      dtype='str')

In [6]:
df.isnull().sum()

#Cuisines --> 9 missing value ,dtype->str

Restaurant ID           0
Restaurant Name         0
Country Code            0
City                    0
Address                 0
Locality                0
Locality Verbose        0
Longitude               0
Latitude                0
Cuisines                9
Average Cost for two    0
Currency                0
Has Table booking       0
Has Online delivery     0
Is delivering now       0
Switch to order menu    0
Price range             0
Aggregate rating        0
Rating color            0
Rating text             0
Votes                   0
dtype: int64

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9551 entries, 0 to 9550
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Restaurant ID         9551 non-null   int64
 1   Restaurant Name       9551 non-null   str
 2   Country Code          9551 non-null   int64
 3   City                  9551 non-null   str
 4   Address               9551 non-null   str
 5   Locality              9551 non-null   str
 6   Locality Verbose      9551 non-null   str
 7   Longitude             9551 non-null   float64
 8   Latitude              9551 non-null   float64
 9   Cuisines              9542 non-null   str
 10  Average Cost for two  9551 non-null   int64
 11  Currency              9551 non-null   str
 12  Has Table booking     9551 non-null   str
 13  Has Online delivery   9551 non-null   str
 14  Is delivering now     9551 non-null   str
 15  Switch to order menu  9551 non-null   str
 16  Price range           9551 non-null   int64
 17  Aggregate rating      9551 non-null   float64
 18  Rating color          9551 non-null   str
 19  Rating text           9551 non-null   str
 20  Votes                 9551 non-null   int64
dtypes: float64(3), int64(5), str(13)
memory usage: 1.5 MB

In [7]:
df[df.duplicated()]

Empty DataFrame
Columns: [Restaurant ID, Restaurant Name, Country Code, City, Address, Locality, Locality Verbose, Longitude, Latitude, Cuisines, Average Cost for two, Currency, Has Table booking, Has Online delivery, Is delivering now, Switch to order menu, Price range, Aggregate rating, Rating color, Rating text, Votes]
Index: []

[0 rows x 21 columns]

In [8]:
df.duplicated().sum()

np.int64(0)

#REMOVING unnecessary column from dataset

In [6]:
#REMOVING unnecessary column from dataset

drop_cols = [
    'Restaurant ID',
    'Restaurant Name',
    'Address',
    'Locality',
    'Locality Verbose',
    'Rating color',
    'Rating text'
]

In [7]:
df=df.drop(columns=drop_cols)

In [8]:
df.head()

,Country Code,City,Longitude,Latitude,Cuisines,Average Cost for two,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Votes
0,162,Makati City,121.027535,14.565443,"French, Japanese, Desserts",1100,Botswana Pula(P),Yes,No,No,No,3,4.8,314
1,162,Makati City,121.014101,14.553708,Japanese,1200,Botswana Pula(P),Yes,No,No,No,3,4.5,591
2,162,Mandaluyong City,121.056831,14.581404,"Seafood, Asian, Filipino, Indian",4000,Botswana Pula(P),Yes,No,No,No,4,4.4,270
3,162,Mandaluyong City,121.056475,14.585318,"Japanese, Sushi",1500,Botswana Pula(P),No,No,No,No,4,4.9,365
4,162,Mandaluyong City,121.057508,14.584450,"Japanese, Korean",1500,Botswana Pula(P),Yes,No,No,No,4,4.8,229

In [9]:
df.columns

Index(['Country Code', 'City', 'Longitude', 'Latitude', 'Cuisines',
       'Average Cost for two', 'Currency', 'Has Table booking',
       'Has Online delivery', 'Is delivering now', 'Switch to order menu',
       'Price range', 'Aggregate rating', 'Votes'],
      dtype='str')

In [10]:
df.isnull().sum()

Country Code            0
City                    0
Longitude               0
Latitude                0
Cuisines                9
Average Cost for two    0
Currency                0
Has Table booking       0
Has Online delivery     0
Is delivering now       0
Switch to order menu    0
Price range             0
Aggregate rating        0
Votes                   0
dtype: int64

TRAIN_TEST_SPLIT DATA

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
x=df.drop(columns=["Aggregate rating"])
y=df["Aggregate rating"]

In [13]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2)

In [14]:
x_train.head()

,Country Code,City,Longitude,Latitude,Cuisines,Average Cost for two,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Votes
2152,1,Gurgaon,77.079802,28.460761,North Indian,700,Indian Rupees(Rs.),No,Yes,No,No,2,35
942,1,Faridabad,77.323461,28.395091,"Fast Food, North Indian",300,Indian Rupees(Rs.),No,No,No,No,1,35
6584,1,New Delhi,77.184919,28.640689,"Raw Meats, Fast Food",400,Indian Rupees(Rs.),No,No,No,No,1,33
3625,1,New Delhi,77.270595,28.656203,North Indian,200,Indian Rupees(Rs.),No,No,No,No,1,0
2995,1,New Delhi,77.268319,28.562174,"Bakery, Desserts, Fast Food",150,Indian Rupees(Rs.),No,No,No,No,1,91

In [15]:
y_train.head()

2152    3.1
942     3.4
6584    2.8
3625    0.0
2995    3.5
Name: Aggregate rating, dtype: float64

In [16]:
x_train.columns

Index(['Country Code', 'City', 'Longitude', 'Latitude', 'Cuisines',
       'Average Cost for two', 'Currency', 'Has Table booking',
       'Has Online delivery', 'Is delivering now', 'Switch to order menu',
       'Price range', 'Votes'],
      dtype='str')

In [17]:
x_train.shape

(7640, 13)

In [20]:
x_train["Cuisines"].value_counts()

Cuisines
North Indian                                                  747
North Indian, Chinese                                         402
Fast Food                                                     293
Chinese                                                       281
North Indian, Mughlai                                         271
                                                             ...
American, Desserts, Diner                                       1
Cafe, Desserts, Beverages                                       1
Italian, Continental, Mexican, Japanese, American, British      1
Mediterranean, Turkish                                          1
Finger Food, European                                           1
Name: count, Length: 1576, dtype: int64

In [21]:
x_train["Currency"].value_counts()

Currency
Indian Rupees(Rs.)        6932
Dollar($)                  391
Pounds(��)                  67
Brazilian Real(R$)          50
Rand(R)                     41
Emirati Diram(AED)          40
NewZealand($)               33
Turkish Lira(TL)            23
Indonesian Rupiah(IDR)      17
Botswana Pula(P)            16
Qatari Rial(QR)             16
Sri Lankan Rupee(LKR)       14
Name: count, dtype: int64

In [23]:
x_train["Has Table booking"].value_counts()

Has Table booking
No     6705
Yes     935
Name: count, dtype: int64

In [24]:
#Has Online delivery', 'Is delivering now', 'Switch to order menu'
x_train["Has Online delivery"].value_counts()

Has Online delivery
No     5668
Yes    1972
Name: count, dtype: int64

In [25]:
x_train["Is delivering now"].value_counts()

Is delivering now
No     7614
Yes      26
Name: count, dtype: int64

In [26]:
x_train["Switch to order menu"].value_counts()

Switch to order menu
No    7640
Name: count, dtype: int64

ML-PIPELINE

In [18]:
# Categorical Columns
cat_cols = [
    'City',
    'Currency',
    'Has Table booking',
    'Has Online delivery',
    'Is delivering now',
    'Switch to order menu'
]

In [19]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error

In [20]:
cuisines_pipe=Pipeline([("imp_cuisines",SimpleImputer(strategy="most_frequent")),
                        ("ohe_cuisines",OneHotEncoder(sparse_output=False,drop="first",handle_unknown="ignore"))])

In [21]:
preprocessor=ColumnTransformer([("cuisines_imp_ohe",cuisines_pipe,["Cuisines"]),
                             ("cat_ohe",OneHotEncoder(sparse_output=False,drop="first",handle_unknown="ignore"),cat_cols)],remainder="passthrough")

#LINEAR_REGRESSION MODEL

In [22]:
pipe_lr=Pipeline([("preprocessor",preprocessor),
                  ("model",LinearRegression())])

In [23]:
pipe_lr.fit(x_train,y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('cuisines_imp_ohe',
                                                  Pipeline(steps=[('imp_cuisines',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('ohe_cuisines',
                                                                   OneHotEncoder(drop='first',
                                                                                 handle_unknown='ignore',
                                                                                 sparse_output=False))]),
                                                  ['Cuisines']),
                                                 ('cat_ohe',
                                                  OneHotEncoder(drop='first',
                                                                handle_unknown='ignore',
                                                                sparse_output=False),
                                                  ['City', 'Currency',
                                                   'Has Table booking',
                                                   'Has Online delivery',
                                                   'Is delivering now',
                                                   'Switch to order menu'])])),
                ('model', LinearRegression())])

In [24]:
# Predict
y_pred_lr = pipe_lr.predict(x_test)

c:\Internship\cognifyz\cognifyzenv\Lib\site-packages\sklearn\preprocessing\_encoders.py:262: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)
c:\Internship\cognifyz\cognifyzenv\Lib\site-packages\sklearn\preprocessing\_encoders.py:262: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)

In [25]:
print(r2_score(y_test,y_pred_lr))

0.36924366829675437

In [26]:
print(mean_squared_error(y_test,y_pred_lr))

1.389223119896191

In [ ]:
#training data
x_train_trf=preprocessor.fit_transform(x_train)

In [37]:
x_train_trf.shape

(7640, 1725)

Transformed Dataset

In [35]:
pd.DataFrame(x_train_trf).head()

,0,1,2,3,4,5,6,7,8,9,...,1715,1716,1717,1718,1719,1720,1721,1722,1723,1724
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,77.079802,28.460761,700.0,2.0,35.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,77.323461,28.395091,300.0,1.0,35.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,77.184919,28.640689,400.0,1.0,33.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,77.270595,28.656203,200.0,1.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,77.268319,28.562174,150.0,1.0,91.0

In [ ]:
pd.DataFrame(x_train_trf,columns=preprocessor.get_feature_names_out()).head()
#here if you want index number same as x_train used index parameter

,"cuisines_imp_ohe__Cuisines_Afghani, Mughlai, Chinese","cuisines_imp_ohe__Cuisines_Afghani, North Indian",cuisines_imp_ohe__Cuisines_African,"cuisines_imp_ohe__Cuisines_African, Portuguese",cuisines_imp_ohe__Cuisines_American,"cuisines_imp_ohe__Cuisines_American, Asian, Burger","cuisines_imp_ohe__Cuisines_American, Asian, European, Seafood","cuisines_imp_ohe__Cuisines_American, Asian, Italian, Seafood","cuisines_imp_ohe__Cuisines_American, Asian, North Indian, Mexican, South Indian","cuisines_imp_ohe__Cuisines_American, BBQ",...,cat_ohe__Currency_Turkish Lira(TL),cat_ohe__Has Table booking_Yes,cat_ohe__Has Online delivery_Yes,cat_ohe__Is delivering now_Yes,remainder__Country Code,remainder__Longitude,remainder__Latitude,remainder__Average Cost for two,remainder__Price range,remainder__Votes
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,77.079802,28.460761,700.0,2.0,35.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,77.323461,28.395091,300.0,1.0,35.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,77.184919,28.640689,400.0,1.0,33.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,77.270595,28.656203,200.0,1.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,77.268319,28.562174,150.0,1.0,91.0

In [39]:
pd.DataFrame(x_train_trf,columns=preprocessor.get_feature_names_out(),index=x_train.index).head()

,"cuisines_imp_ohe__Cuisines_Afghani, Mughlai, Chinese","cuisines_imp_ohe__Cuisines_Afghani, North Indian",cuisines_imp_ohe__Cuisines_African,"cuisines_imp_ohe__Cuisines_African, Portuguese",cuisines_imp_ohe__Cuisines_American,"cuisines_imp_ohe__Cuisines_American, Asian, Burger","cuisines_imp_ohe__Cuisines_American, Asian, European, Seafood","cuisines_imp_ohe__Cuisines_American, Asian, Italian, Seafood","cuisines_imp_ohe__Cuisines_American, Asian, North Indian, Mexican, South Indian","cuisines_imp_ohe__Cuisines_American, BBQ",...,cat_ohe__Currency_Turkish Lira(TL),cat_ohe__Has Table booking_Yes,cat_ohe__Has Online delivery_Yes,cat_ohe__Is delivering now_Yes,remainder__Country Code,remainder__Longitude,remainder__Latitude,remainder__Average Cost for two,remainder__Price range,remainder__Votes
2152,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,77.079802,28.460761,700.0,2.0,35.0
942,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,77.323461,28.395091,300.0,1.0,35.0
6584,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,77.184919,28.640689,400.0,1.0,33.0
3625,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,77.270595,28.656203,200.0,1.0,0.0
2995,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,77.268319,28.562174,150.0,1.0,91.0

In [40]:
#testing data
x_test_trf=preprocessor.transform(x_test)

c:\Internship\cognifyz\cognifyzenv\Lib\site-packages\sklearn\preprocessing\_encoders.py:262: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)
c:\Internship\cognifyz\cognifyzenv\Lib\site-packages\sklearn\preprocessing\_encoders.py:262: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)

#why this warning comes :
"""During training, the encoder learned cuisine categories from X_train only.

Example:North Indian
Chinese
Bakery
Japanese

But in X_test, some cuisine combinations appear that were never present in X_train:French, Bakery
Greek, Mediterranean
Italian, Seafood 
Since those categories were never seen during .fit(), sklearn calls them unknown categorie

Since you used:
handle_unknown='ignore'"""

In [ ]:
"""During categorical encoding, some cuisine categories present in the testing data were not observed in the training data. To handle this safely, OneHotEncoder was configured with handle_unknown='ignore', ensuring unseen categories were encoded without causing errors."""

In [44]:
x_test_trf.shape

(1911, 1725)

In [43]:
pd.DataFrame(x_test_trf).head()

,0,1,2,3,4,5,6,7,8,9,...,1715,1716,1717,1718,1719,1720,1721,1722,1723,1724
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,77.230412,28.573123,600.0,2.0,308.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,77.227043,28.647762,200.0,1.0,545.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.000000,0.000000,500.0,2.0,2.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,77.072051,28.510369,300.0,1.0,4.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,76.987930,28.602468,150.0,1.0,0.0

In [45]:
pd.DataFrame(x_test_trf,columns=preprocessor.get_feature_names_out(),index=x_test.index).head()

,"cuisines_imp_ohe__Cuisines_Afghani, Mughlai, Chinese","cuisines_imp_ohe__Cuisines_Afghani, North Indian",cuisines_imp_ohe__Cuisines_African,"cuisines_imp_ohe__Cuisines_African, Portuguese",cuisines_imp_ohe__Cuisines_American,"cuisines_imp_ohe__Cuisines_American, Asian, Burger","cuisines_imp_ohe__Cuisines_American, Asian, European, Seafood","cuisines_imp_ohe__Cuisines_American, Asian, Italian, Seafood","cuisines_imp_ohe__Cuisines_American, Asian, North Indian, Mexican, South Indian","cuisines_imp_ohe__Cuisines_American, BBQ",...,cat_ohe__Currency_Turkish Lira(TL),cat_ohe__Has Table booking_Yes,cat_ohe__Has Online delivery_Yes,cat_ohe__Is delivering now_Yes,remainder__Country Code,remainder__Longitude,remainder__Latitude,remainder__Average Cost for two,remainder__Price range,remainder__Votes
3245,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,77.230412,28.573123,600.0,2.0,308.0
2904,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,77.227043,28.647762,200.0,1.0,545.0
7928,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.000000,0.000000,500.0,2.0,2.0
2233,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,77.072051,28.510369,300.0,1.0,4.0
5709,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,76.987930,28.602468,150.0,1.0,0.0

In [ ]:
# x_train_pipe_df.to_csv("../dataset/transformed_dataset.csv", index=False)-->but the problem is it will saved only x_train_pipe_df but i want whole data so used-->

In [35]:
"""X_transformed = preprocessor.fit_transform(x)

X_transformed_df = pd.DataFrame(
    X_transformed,
    columns=preprocessor.get_feature_names_out()
)

X_transformed_df.to_csv("../dataset/transformed_dataset.csv", index=False)"""

#optional to save the transformed data

'X_transformed = preprocessor.fit_transform(x)\n\nX_transformed_df = pd.DataFrame(\n    X_transformed,\n    columns=preprocessor.get_feature_names_out()\n)\n\nX_transformed_df.to_csv("../dataset/transformed_dataset.csv", index=False)'

DECISION_TREE_REGRESSION

In [ ]:
#using DecisionTreeRegressor

In [51]:
from sklearn.tree import DecisionTreeRegressor

In [71]:
cuisines_pipe=Pipeline([("imp_cuisines",SimpleImputer(strategy="most_frequent")),
                        ("ohe_cuisines",OneHotEncoder(sparse_output=False,drop="first",handle_unknown="ignore"))])

In [72]:
preprocessor=ColumnTransformer([("cuisines_imp_ohe",cuisines_pipe,["Cuisines"]),
                             ("cat_ohe",OneHotEncoder(sparse_output=False,drop="first",handle_unknown="ignore"),cat_cols)],remainder="passthrough")

In [73]:
pipe_dt=Pipeline([("preprocessor",preprocessor),
                  ("dt_model",DecisionTreeRegressor(random_state=42))])

In [74]:
pipe_dt.fit(x_train,y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('cuisines_imp_ohe',
                                                  Pipeline(steps=[('imp_cuisines',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('ohe_cuisines',
                                                                   OneHotEncoder(drop='first',
                                                                                 handle_unknown='ignore',
                                                                                 sparse_output=False))]),
                                                  ['Cuisines']),
                                                 ('cat_ohe',
                                                  OneHotEncoder(drop='first',
                                                                handle_unknown='ignore',
                                                                sparse_output=False),
                                                  ['City', 'Currency',
                                                   'Has Table booking',
                                                   'Has Online delivery',
                                                   'Is delivering now',
                                                   'Switch to order menu'])])),
                ('dt_model', DecisionTreeRegressor(random_state=42))])

In [75]:
y_pred_dt=pipe_dt.predict(x_test)

c:\Internship\cognifyz\cognifyzenv\Lib\site-packages\sklearn\preprocessing\_encoders.py:262: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)
c:\Internship\cognifyz\cognifyzenv\Lib\site-packages\sklearn\preprocessing\_encoders.py:262: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)

In [76]:
print("r2_score:",r2_score(y_test,y_pred_dt))

r2_score: 0.9193594347875287

In [77]:
print("MSE :", mean_squared_error(y_test, y_pred_dt))

MSE : 0.17760858189429615

In [78]:
import pandas as pd

results = pd.DataFrame({
    "Model": ["Linear Regression", "Decision Tree Regressor"],
    "R2 Score": [
        r2_score(y_test, y_pred_lr),
        r2_score(y_test, y_pred_dt)
    ],
    "MSE": [
        mean_squared_error(y_test, y_pred_lr),
        mean_squared_error(y_test, y_pred_dt)
    ]
})

results

                     Model  R2 Score       MSE
0        Linear Regression  0.369244  1.389223
1  Decision Tree Regressor  0.919359  0.177609

In [ ]:
"""Two regression models were trained and evaluated:
Linear Regression and Decision Tree Regressor.

Linear Regression achieved an R² score of 0.3692 and an MSE of 1.3892.

Decision Tree Regressor achieved an R² score of 0.9178 and an MSE of 0.1811.

Since the Decision Tree Regressor has a significantly higher R² score and lower Mean Squared Error, it performs much better on this dataset and was selected as the final model for restaurant rating prediction."""

In [ ]:
#here we save decision_tree algorithm
import pickle

pickle.dump(pipe_dt, open("../models/restaurant_rating_model.pkl", "wb"))

In [79]:
feature_names = pipe_dt.named_steps['preprocessor'].get_feature_names_out()

importance_df = pd.DataFrame({
    "Feature": feature_names,
    "Importance": pipe_dt.named_steps['dt_model'].feature_importances_
})

importance_df.sort_values(
    by="Importance",
    ascending=False
).head(10)

                                                Feature  Importance
1724                                   remainder__Votes    0.947450
1720                               remainder__Longitude    0.013665
1721                                remainder__Latitude    0.009695
1722                    remainder__Average Cost for two    0.004814
1708               cat_ohe__Currency_Indian Rupees(Rs.)    0.003275
1705               cat_ohe__Currency_Brazilian Real(R$)    0.000907
1717                   cat_ohe__Has Online delivery_Yes    0.000745
1145   cuisines_imp_ohe__Cuisines_North Indian, Chinese    0.000692
48    cuisines_imp_ohe__Cuisines_American, Fast Food...    0.000569
1402        cuisines_imp_ohe__Cuisines_Pizza, Fast Food    0.000506

#The analysis reveals that Votes is the strongest predictor of restaurant ratings, followed by location-related features and restaurant pricing information. This indicates that customer engagement and restaurant location play a significant role in determining restaurant ratings.